### ISSUE TITLE
License Questions

### ISSUE THREAD

**Issue by FatBrownDog** [pragmatic-engineering/svelte-form-builder-community#14]
Q1. If I buy once, can I use this on 2 websites?

Q2. If I allow my customers to make forms, but don't give them the source code, is that OK?

Q3. If I do work-for-hire, my customer buys a license for the project and provides it to me, is that permitted?

**Comment by Jojoshua** [comment]
> Q1. If I buy once, can I use this on 2 websites?

Yes, as many as you wish.

> Q2. If I allow my customers to make forms, but don't give them the source code, is that OK?

Yes, that is a typical use case.

> Q3. If I do work-for-hire, my customer buys a license for the project and provides it to me, is that permitted?

Yes, that's fine.
