### ISSUE TITLE
Need a min-length for text field

### ISSUE THREAD

**Issue by FatBrownDog** [pragmatic-engineering/svelte-form-builder-community#15]
I need min-length for text-field.
Possible?

Reason.
Field requirement. Between 3 (min) to 30 (max) characters.

**Comment by Jojoshua** [comment]
Likely possible either through adding the html attribute or adding a pattern property for regex

**Comment by Jojoshua** [comment]
This can be done per field in the formdefinition or done for all fields of that type using componentOptions. The attributes will also show up in the interface. This works for any desired html attributes.

	let formJSON: FormDefinition[] = [
		{
			tab: { id: 'one', tabOrder: 1, label: 'One' },
			rows: [
				{
					rowID: 1,
					fields: [
						{
							componentName: 'Text',
							htmlAttributes: {
								maxlength: 30,
								minlength: 4
							}
						}
					]
				}
			]
		}
	];
	
	let options: BuilderOptions = {
		view: 'build',
		theme: 'Default',
		componentOptions: [
			{
				componentName: 'Text',
				htmlAttributes: {
					maxlength: 30,
					minlength: 3
				}
			}
		],
		formDefinition: formJSON
	};


![image](https://github.com/pragmatic-engineering/svelte-form-builder-community/assets/5598169/a3ec8941-6fdd-4920-9ed2-045e9b1385d6)
