### ISSUE TITLE
Need a URL and Email field with validation.

### ISSUE THREAD

**Issue by FatBrownDog** [pragmatic-engineering/svelte-form-builder-community#16]
I need text field with URL and EMail validation.

**Comment by Jojoshua** [comment]
I think this can be done by adding custom html attribute or pattern.

**Comment by Jojoshua** [comment]
Fixed via https://github.com/pragmatic-engineering/svelte-form-builder-community/commit/3c0b9b916ae5ab9c5a46154913b6a19612ab27ea

Example
```

let formJSON: FormDefinition[] = [
		{
			tab: { id: 'one', tabOrder: 1, label: 'One' },
			rows: [
				{
					rowID: 1,
					fields: [
						{
							componentName: 'Text',
							htmlAttributes: {
								type: 'email'
							}
						}
					]
				}
			]
		}
	];

	let options: BuilderOptions = {
		view: 'build',
		theme: 'Default',
		formDefinition: formJSON
	};
```

![image](https://github.com/pragmatic-engineering/svelte-form-builder-community/assets/5598169/3e1113a8-f3f2-4ffb-b459-b633372e2b17)
