### ISSUE TITLE
All uppercase, all lower-case text field

### ISSUE THREAD

**Issue by FatBrownDog** [pragmatic-engineering/svelte-form-builder-community#18]
I need a text field with all-upper case and all-lower case letters as option.

**Comment by Jojoshua** [comment]
Hmm prob could add a css class to the field which does this or possibly hook into a change event and modify with JavaScript if you are in control of the overall codebase.

**Comment by Jojoshua** [comment]
This is actually pretty easy with just the style attribute

```

	let formJSON: FormDefinition[] = [
		{
			tab: { id: 'one', tabOrder: 1, label: 'One' },
			rows: [
				{
					rowID: 1,
					fields: [
						{
							componentName: 'Text',
							htmlAttributes: {
								style: 'text-transform:lowercase'
							}
						},
						{
							componentName: 'Text',
							htmlAttributes: {
								style: 'text-transform:uppercase'
							}
						}
					]
				}
			]
		}
	];

	let options: BuilderOptions = {
		view: 'build',
		theme: 'Default',
		formDefinition: formJSON
	};
```


![image](https://github.com/pragmatic-engineering/svelte-form-builder-community/assets/5598169/9675bc43-1354-476a-8ec2-b7dc6ef46310)
