### ISSUE TITLE
Allow fractional values for time.

### ISSUE THREAD

**Issue by FatBrownDog** [pragmatic-engineering/svelte-form-builder-community#20]
I need, like, 

4 hours 10 minutes.
4 hours 30 minutes.

Example.
5, 10, 15, 20, 25 instead of minutes for time field.
15, 30, 45, 00.
0, 30 minutes

**Comment by Jojoshua** [comment]
To do something like this you could....
- Create your own custom component 
- Use 2 standard fields, one for hours and another for minutes
