### ISSUE TITLE
Using a form once built

### ISSUE THREAD

**Issue by legsak1mbo** [pragmatic-engineering/svelte-form-builder-community#4]
I'm sure I've missed something really obvious but I can't see anything in the docs. How does one set an action and then render a form on a page once built?

**Comment by Jojoshua** [comment]
No it's my fault. I didn't make that clear in the docs. To do this you set the view property to 'render'. I will update the docs.

**Comment by legsak1mbo** [comment]
Grand, thanks. I still can't see where to set the action/endpoint or HTTP method for the form though?

**Comment by legsak1mbo** [comment]
OK, that does make perfect sense. In that case my next question would be how do we bind events to the submit button on the form and/or get the data?

I tried adding on:submit to the FormBuilder component on my page but no dice.

**Comment by Jojoshua** [comment]
I think you can use the standard onclick event like this https://svelte-form-builder-docs.vercel.app/en/components/standard/Button

and then use the RenderAPI class (which is exported https://github.com/pragmatic-engineering/svelte-form-builder-community/blob/master/src/lib/index.ts)  to then call getData(). I need to make that clearer as well. 

The BuilderAPI is intended for managing the "definition" while building and the RenderAPI is intended for managing "instances" of the definition when it's rendered.

**Comment by legsak1mbo** [comment]
OK, I'll try that. Just to make sure I haven't missed anything - you can't bind events in the builder at the moment?

**Comment by Jojoshua** [comment]
Yeah pretty sure events are only done through code,not the ui.
